<?php

namespace AppBundle\Repository;

/**
 * RaceMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
